name: omniedge freebsd build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      env:
        description: env of the action
        default: prod
        required: false
      tag:
        description: tag ( if tag is not empty, env is always prod)
        required: false
jobs:
  testfreebsd:
    runs-on: macos-12
    name: A job to run test FreeBSD
    steps:
      - name: setup env to prod if tag is not empty
        if: ${{ env.TAG }}
        run: |
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          
      - name: Checkout without tag
        if: ${{ !env.TAG }}
        uses: actions/checkout@master

      - name: Checkout with tag
        uses: actions/checkout@master
        if: ${{ env.TAG }}
        with:
          ref: ${{ env.TAG }}

      - name: Show CPU Model and Free Space
        if: ${{ !matrix.os == 'macos-latest' }}
        run: |
          echo -e "Total CPU cores\t: $(nproc)"
          cat /proc/cpuinfo | grep 'model name'
          free -h
      - name: Show system info
        run: |
          echo -e "system info: $(uname -a)"
      - uses: actions/checkout@v2
      - name: prepare
        id: test
        uses: vmactions/freebsd-vm@v0.1.8
        with:
          usesh: true
          run: |
            pkg update
            free -h
            pkg install -y bash go gmake git openssl zip autoconf automake libtool upx
            chsh -s bash
            make generate
            BUILD_ENV=${{ env.ENVIRONMENT }} make build-freebsd
            upx -9 -k ./out/omniedge
            zip -j ./omniedge-${{ github.ref_name }}-freebsd-13.1.zip ./out/omniedge
      
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          path: omniedge-${{ github.ref_name }}-freebsd-13.1.zip
          name: omniedge-${{ github.ref_name }}-freebsd-13.1.zip
          if-no-files-found: error
          
      - name: Upload package to GitHub Release
        uses: svenstaro/upload-release-action@v2
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          overwrite: true
          file: omniedge-${{ github.ref_name }}-freebsd-13.1.zip
          tag: ${{ github.ref }}